### ISSUE TITLE
Xenome doesnt finish - takes very long time

### ISSUE THREAD

**Issue by obwan74** [data61/gossamer#16] opened 2018-01-15 16:22 UTC
Hi, 
I finished indexing the genomes. If I use -M 124 and high thread number somehow indexing keeps on going and doesnt finish. If I use low memory -M 64 and 8 threads indexing completed fairly fast. 

However, for xenome classify  whether I specify -M 100 or no -M option, xenome classify keeps on going and doesnt end. I checked the total number of reads from input fastq and they match total reads classified into host, graft, combined etc. bins. It appears xenome does not finish itself after classifying reads successfully. 
what could be the issue?

**Comment by Deguerre** [comment] 2018-01-15 23:33
G'day. This is almost certainly the same problem as issue #9.

**Comment by splaisan** [comment] 2018-03-04 09:28
I missed that one but confirm, I could not run with more than 8 threads (I have 88) and 96GB RAM (I have 512GB)
Takes ages while I have plenty of resources unused.
Please help

**Comment by Deguerre** [comment] 2018-07-10 02:39
Definitely a duplicate of #9 .

**Closed** 2018-07-10 02:39 UTC
